/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestorbasedatos;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gabriela Diaz R
 */
public class Funciones extends javax.swing.JPanel {

    /**
     * Creates new form Funciones
     */
    public Funciones() {
        initComponents();
    }
    int index=0;
    String funcioname="";
     ArrayList<nodoProcedimiento> variablesp = new ArrayList<nodoProcedimiento>();
    ArrayList<nodoProcedimiento> variablesd = new ArrayList<nodoProcedimiento>();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jTextField3 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jTextField4 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton6 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Funciones");
        add(jLabel1);
        jLabel1.setBounds(91, 26, 105, 29);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestorbasedatos/Firebird_logo.png"))); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(23, 15, 50, 50);

        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        add(jScrollPane1);
        jScrollPane1.setBounds(60, 130, 130, 160);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Listar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(60, 80, 130, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("CREAR/MODIFICAR FUNCIONES");
        add(jLabel3);
        jLabel3.setBounds(260, 20, 320, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Nombre:");
        add(jLabel4);
        jLabel4.setBounds(260, 60, 120, 15);
        add(jTextField1);
        jTextField1.setBounds(320, 60, 330, 20);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CREAR", "MODIFICAR" }));
        add(jComboBox1);
        jComboBox1.setBounds(260, 90, 390, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Parametros:");
        add(jLabel5);
        jLabel5.setBounds(260, 180, 140, 14);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Nombre:");
        add(jLabel6);
        jLabel6.setBounds(260, 210, 60, 15);
        add(jTextField2);
        jTextField2.setBounds(330, 210, 320, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Tipo Dato:");
        add(jLabel7);
        jLabel7.setBounds(260, 250, 80, 15);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "INT", "VARCHAR", "DATE", "FLOAT" }));
        jComboBox2.setToolTipText("");
        jComboBox2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox2MouseClicked(evt);
            }
        });
        add(jComboBox2);
        jComboBox2.setBounds(330, 250, 260, 20);
        add(jTextField3);
        jTextField3.setBounds(600, 250, 50, 20);

        jCheckBox1.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("PARAMETRO");
        add(jCheckBox1);
        jCheckBox1.setBounds(260, 300, 100, 23);

        jCheckBox3.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox3.setText("DECLARE");
        add(jCheckBox3);
        jCheckBox3.setBounds(360, 300, 81, 23);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Returns:");
        add(jLabel9);
        jLabel9.setBounds(260, 120, 70, 15);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestorbasedatos/check.png"))); // NOI18N
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(600, 280, 40, 39);

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Motivo:");
        add(jLabel10);
        jLabel10.setBounds(260, 280, 70, 15);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "INT", "VARCHAR", "DATE", "FLOAT" }));
        add(jComboBox3);
        jComboBox3.setBounds(260, 140, 320, 20);
        add(jTextField4);
        jTextField4.setBounds(590, 140, 60, 20);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Tipo Dato", "Motivo"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jScrollPane3.setViewportView(jScrollPane2);

        add(jScrollPane3);
        jScrollPane3.setBounds(260, 330, 410, 200);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Sentencia :");
        add(jLabel8);
        jLabel8.setBounds(260, 540, 70, 15);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane4.setViewportView(jTextArea1);

        add(jScrollPane4);
        jScrollPane4.setBounds(260, 560, 410, 150);

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setText("Listo");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        add(jButton3);
        jButton3.setBounds(260, 720, 410, 40);

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setText("Mostrar DDL");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        add(jButton4);
        jButton4.setBounds(20, 470, 210, 40);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Borrar Funcion");
        add(jLabel11);
        jLabel11.setBounds(40, 340, 160, 20);

        jLabel12.setForeground(new java.awt.Color(153, 0, 0));
        jLabel12.setText("Seleccionar de la lista funcion.");
        add(jLabel12);
        jLabel12.setBounds(40, 360, 190, 20);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestorbasedatos/trash.png"))); // NOI18N
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        add(jButton5);
        jButton5.setBounds(40, 390, 60, 50);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane5.setViewportView(jTextArea2);

        add(jScrollPane5);
        jScrollPane5.setBounds(20, 520, 210, 200);

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton6.setText("BACK");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        add(jButton6);
        jButton6.setBounds(30, 730, 120, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        DefaultListModel listModel = new DefaultListModel();

        ArrayList<String> tmp = new ArrayList<String>();
        tmp = GestorBaseDatos.conexion.ListarFunciones();
        int x = 0;
        while (x < tmp.size()) {
            listModel.addElement(tmp.get(x));
            x++;
        }

        jList1.setModel(listModel);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        index = 0;
        funcioname = "";
        JList list = (JList) evt.getSource();
        if (evt.getClickCount() == 2) {
            index = list.locationToIndex(evt.getPoint());
            funcioname = jList1.getModel().getElementAt(index).toString();

        }
    }//GEN-LAST:event_jList1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        DefaultTableModel n = (DefaultTableModel) jTable1.getModel();
        String nombreC = jTextField2.getText().trim();
        jTextField2.setText("");
        String tipodato = jComboBox2.getSelectedItem().toString();
        String motivo = "";
        nodoProcedimiento tmp = new nodoProcedimiento(nombreC, tipodato, motivo);
        if (tipodato.equals("VARCHAR")) {
            tipodato = "VARCHAR (" + jTextField3.getText() + ")";

        }

        if (jCheckBox1.isSelected()) {
            motivo = "PARAMETRO";
            variablesp.add(tmp);
        } 
         else if (jCheckBox3.isSelected()) {
            motivo = "DECLARE";
            variablesd.add(tmp);
        }

        n.addRow(new Object[]{nombreC, tipodato, motivo});

    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        String parameters = "";
        String returnss = jComboBox3.getSelectedItem().toString();
        String declaress = "";
        String nombrep = jTextField1.getText();
        String sentencia = jTextArea1.getText();

        
        if(returnss.equals("VARCHAR")){
            returnss="VARCHAR ("+jTextField4.getText()+")";
        }
        for (int x = 0; x < variablesp.size(); x++) {
            parameters += " " + variablesp.get(x).nombre + " " + variablesp.get(x).tipodato;
            if (x != variablesp.size() - 1) {
                parameters += " ,";
            }
        }
        for (int x = 0; x < variablesd.size(); x++) {
            declaress += " DECLARE VARIABLE " + variablesd.get(x).nombre + " " + variablesd.get(x).tipodato + " ; ";

        }

        if (jComboBox1.getSelectedItem().toString().equals("CREAR")) {
            GestorBaseDatos.conexion.CrearFunciones(nombrep, parameters, returnss, declaress, sentencia);
        } else if (jComboBox1.getSelectedItem().toString().equals("MODIFICAR")) {
            GestorBaseDatos.conexion.ModificarFunciones(nombrep, parameters, returnss, declaress, sentencia);
        }

        DefaultTableModel n = (DefaultTableModel) jTable1.getModel();
        n.setRowCount(0);
        jTextField1.setText("");
        jTextArea1.setText("");
        variablesp.clear();
        variablesd.clear();
    }//GEN-LAST:event_jButton3MouseClicked

    private void jComboBox2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        jTextArea2.setText("");
        String source= GestorBaseDatos.conexion.Funcionesddl(funcioname);
        String ddl= "CREATE FUNCTION \u2002"+funcioname.trim()+"\u2002 AS \n"+source;
        jTextArea2.setText(ddl);
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        GestorBaseDatos.conexion.BorrarFuncion(funcioname);
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        Principal p = new Principal();
        GestorBaseDatos.frame.setPanel(p);
    }//GEN-LAST:event_jButton6MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
