/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestorbasedatos;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gabriela Diaz R
 */
public class Triggers extends javax.swing.JPanel {

    /**
     * Creates new form Triggers
     */
    public Triggers() {
        initComponents();
        ArrayList<String> tables = GestorBaseDatos.conexion.ListasTablas();

        for (int x = 0; x < tables.size(); x++) {

            jComboBox1.addItem(tables.get(x));

        }

    }
    int index = 0;
    String triggername = "";
    ArrayList<nodoProcedimiento> variablesd = new ArrayList<nodoProcedimiento>();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jCheckBox3 = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton5 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jCheckBox4 = new javax.swing.JCheckBox();
        jComboBox5 = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestorbasedatos/Firebird_logo.png"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(30, 20, 50, 50);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Triggers");
        add(jLabel2);
        jLabel2.setBounds(90, 30, 110, 30);

        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        add(jScrollPane1);
        jScrollPane1.setBounds(30, 130, 190, 180);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("List");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(30, 80, 190, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Borrar Trigger");
        add(jLabel3);
        jLabel3.setBounds(30, 640, 160, 30);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Estado:");
        add(jLabel4);
        jLabel4.setBounds(580, 80, 50, 20);
        add(jTextField1);
        jTextField1.setBounds(310, 80, 210, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Nombre:");
        add(jLabel5);
        jLabel5.setBounds(250, 80, 60, 14);

        add(jComboBox1);
        jComboBox1.setBounds(310, 120, 210, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Tiempo:");
        add(jLabel6);
        jLabel6.setBounds(250, 160, 90, 14);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ACTIVE", "INACTIVE" }));
        add(jComboBox2);
        jComboBox2.setBounds(560, 120, 100, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Table :");
        add(jLabel7);
        jLabel7.setBounds(250, 120, 50, 14);

        jCheckBox1.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("INSERT");
        add(jCheckBox1);
        jCheckBox1.setBounds(400, 180, 100, 23);

        jCheckBox2.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox2.setText("DELETE");
        add(jCheckBox2);
        jCheckBox2.setBounds(600, 180, 90, 23);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "BEFORE", "AFTER" }));
        add(jComboBox3);
        jComboBox3.setBounds(250, 180, 120, 20);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Variables a declarar:");
        add(jLabel8);
        jLabel8.setBounds(250, 220, 140, 14);

        jCheckBox3.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox3.setText("UPDATE");
        add(jCheckBox3);
        jCheckBox3.setBounds(500, 180, 90, 23);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Eventos:");
        add(jLabel9);
        jLabel9.setBounds(400, 160, 80, 10);
        add(jTextField2);
        jTextField2.setBounds(310, 250, 210, 20);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Sentencia:");
        add(jLabel10);
        jLabel10.setBounds(250, 500, 110, 14);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "INTEGER", "VARCHAR", "DATE", "FLOAT" }));
        add(jComboBox4);
        jComboBox4.setBounds(310, 290, 210, 20);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Nombre:");
        add(jLabel11);
        jLabel11.setBounds(250, 250, 60, 14);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Tipo Dato"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jScrollPane3.setViewportView(jScrollPane2);

        add(jScrollPane3);
        jScrollPane3.setBounds(250, 320, 420, 170);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestorbasedatos/check.png"))); // NOI18N
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(600, 250, 50, 50);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane4.setViewportView(jTextArea1);

        add(jScrollPane4);
        jScrollPane4.setBounds(250, 520, 420, 140);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Tipo:");
        add(jLabel12);
        jLabel12.setBounds(260, 290, 60, 14);

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setText("CREAR/MODIFICAR TRIGGER");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        add(jButton3);
        jButton3.setBounds(250, 670, 420, 50);

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setText("Mostrar DDL");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        add(jButton4);
        jButton4.setBounds(30, 320, 190, 40);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane5.setViewportView(jTextArea2);

        add(jScrollPane5);
        jScrollPane5.setBounds(30, 370, 190, 180);

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton5.setText("Modificar Trigger");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        add(jButton5);
        jButton5.setBounds(30, 560, 190, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("CREAR/MODIFICAR TRIGGER");
        add(jLabel13);
        jLabel13.setBounds(250, 50, 200, 14);

        jLabel14.setForeground(new java.awt.Color(153, 0, 0));
        jLabel14.setText("Seleccionar de la lista funcion.");
        add(jLabel14);
        jLabel14.setBounds(30, 670, 190, 20);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestorbasedatos/trash.png"))); // NOI18N
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        add(jButton6);
        jButton6.setBounds(30, 700, 60, 50);

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton7.setText("Back");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });
        add(jButton7);
        jButton7.setBounds(563, 733, 110, 40);
        add(jTextField3);
        jTextField3.setBounds(530, 290, 50, 20);

        jCheckBox4.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox4.setText("MODIFICAR");
        add(jCheckBox4);
        jCheckBox4.setBounds(560, 50, 100, 23);

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ACTIVE", "INACTIVE" }));
        add(jComboBox5);
        jComboBox5.setBounds(30, 600, 190, 20);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
     GestorBaseDatos.conexion.BorrarTrigger(triggername);
        
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        DefaultListModel listModel = new DefaultListModel();

        ArrayList<String> tmp = new ArrayList<String>();
        tmp = GestorBaseDatos.conexion.ListarTriggers();
        int x = 0;
        while (x < tmp.size()) {
            listModel.addElement(tmp.get(x));
            x++;
        }

        jList1.setModel(listModel);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        DefaultTableModel n = (DefaultTableModel) jTable1.getModel();
        String nombreC = jTextField2.getText().trim();
        jTextField2.setText("");
        String tipodato = jComboBox4.getSelectedItem().toString();
        String motivo = "DECLARE";
       
        if (tipodato.equals("VARCHAR")) {
            tipodato = "VARCHAR (" + jTextField3.getText() + ")";

        }
         nodoProcedimiento tmp = new nodoProcedimiento(nombreC, tipodato, motivo);
        variablesd.add(tmp);

        n.addRow(new Object[]{nombreC, tipodato});
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        String nametrig = jTextField1.getText();
        jTextField1.setText("");
        String nametable= jComboBox1.getSelectedItem().toString().trim();
        String estado = jComboBox2.getSelectedItem().toString();
        String tiempo= jComboBox3.getSelectedItem().toString();
        String eventos="";
        int count=0;
        
        if(jCheckBox1.isSelected()){
            eventos=" INSERT";
            count+=1;
        }
        if(jCheckBox3.isSelected()){
            if(count!=0){
               eventos+=" OR UPDATE"; 
            }
            else{
               eventos+=" UPDATE"; 
            }
            count +=1;
        }
        if(jCheckBox2.isSelected()){
            if(count!=0){
               eventos+=" OR DELETE"; 
            }
            else{
               eventos+=" DELETE"; 
            }
            count +=1;
        }
        String declares="";
        for (int x=0 ; x< variablesd.size(); x++){
            declares+= " DECLARE VARIABLE "+ variablesd.get(x).nombre+" "+variablesd.get(x).tipodato+" ;";
        }
        String sentencia=jTextArea1.getText();
        jTextArea1.setText("");
       
        if(!jCheckBox4.isSelected()){
        String query="CREATE TRIGGER "+nametrig+" FOR "+nametable+" "+estado+" "+tiempo+" "+eventos+" AS "+declares+" BEGIN "+sentencia+" END;";
         GestorBaseDatos.conexion.CrearModificarTrigger(query);
        }
        else{
             String query="ALTER TRIGGER "+nametrig+" "+estado+" "+tiempo+" "+eventos+" AS "+declares+" BEGIN "+sentencia+" END;";
         GestorBaseDatos.conexion.CrearModificarTrigger(query);
        }
      
          DefaultTableModel n = (DefaultTableModel) jTable1.getModel();
          n.setRowCount(0);
          variablesd.clear();
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        ArrayList <String> data= GestorBaseDatos.conexion.Triggersddl(triggername);
        String ddl="CREATE TRIGGER "+triggername+" \nFOR \n"+data.get(0)+"\n"+data.get(3)+"\n"+data.get(1)+"\n"+data.get(2);
        jTextArea2.setText(ddl);
    }//GEN-LAST:event_jButton4MouseClicked

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
         index = 0;
        triggername = "";
        JList list = (JList) evt.getSource();
        if (evt.getClickCount() == 2) {
            index = list.locationToIndex(evt.getPoint());
           triggername = jList1.getModel().getElementAt(index).toString();

        }
    }//GEN-LAST:event_jList1MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        String estado= jComboBox5.getSelectedItem().toString().trim();
        GestorBaseDatos.conexion.ModificarEstadoTrigger(triggername, estado);
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
     Principal p =new Principal();
     GestorBaseDatos.frame.setPanel(p);
    }//GEN-LAST:event_jButton7MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
