/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestorbasedatos;

import java.awt.Color;
import java.awt.event.ActionListener;
import java.io.File;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author Gabriela Diaz R
 */
public class Principal extends javax.swing.JPanel {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestorbasedatos/addconection.png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(280, 220, 49, 59);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestorbasedatos/connect.png"))); // NOI18N
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(330, 220, 48, 59);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestorbasedatos/trash.png"))); // NOI18N
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        add(jButton4);
        jButton4.setBounds(380, 220, 47, 59);

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setText("Tablas");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        add(jButton3);
        jButton3.setBounds(200, 300, 150, 40);

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton5.setText("Indices");
        add(jButton5);
        jButton5.setBounds(200, 350, 150, 40);

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton6.setText("Procedimientos");
        add(jButton6);
        jButton6.setBounds(200, 400, 150, 40);

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton7.setText("Funciones");
        add(jButton7);
        jButton7.setBounds(200, 450, 150, 40);

        jButton8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton8.setText("Triggers");
        add(jButton8);
        jButton8.setBounds(370, 300, 150, 40);

        jButton9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton9.setText("Usuarios");
        add(jButton9);
        jButton9.setBounds(290, 500, 150, 40);

        jButton10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton10.setText("Base de Datos");
        add(jButton10);
        jButton10.setBounds(370, 450, 150, 40);

        jButton11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton11.setText("Vistas");
        add(jButton11);
        jButton11.setBounds(370, 350, 150, 40);

        jButton12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton12.setText("Checks");
        add(jButton12);
        jButton12.setBounds(370, 400, 150, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestorbasedatos/Logo.png"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(150, 100, 410, 70);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
            JFrame jFrame1 = new JFrame();
            jFrame1.setSize(220, 200);
            jFrame1.setLocationRelativeTo(null);
            jFrame1.setResizable(false);
            jFrame1.setLayout(null);
            jFrame1.getContentPane().setBackground(Color.white);

            JButton boton = new JButton("CREATE");
            boton.setBounds(60, 100, 100, 20);

            jFrame1.add(boton);
            JTextField texto = new JTextField();
            texto.setBounds(60, 65, 100, 20);
            jFrame1.add(texto);

            JLabel titulo = new JLabel();

            titulo.setText("Nombre Base de Datos= ");
            titulo.setBounds(60, 0, 120, 50);
            jFrame1.add(titulo);
            jFrame1.setVisible(true);

            boton.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(java.awt.event.ActionEvent ae) {
                    String namedb= texto.getText();
                    GestorBaseDatos.conexion.CrearConexion(namedb);
                   
                }
            });
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        JFileChooser files = new JFileChooser();
        files.showSaveDialog(null);
        File selectedFile = files.getSelectedFile();
        String path = selectedFile.getAbsolutePath();
        String url= "jdbc:firebirdsql:localhost/3050:"+path;
        GestorBaseDatos.conexion.Conectar(url);
        
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        JFileChooser files = new JFileChooser();
        files.showSaveDialog(null);
        File selectedFile = files.getSelectedFile();
        String path = selectedFile.getAbsolutePath();
       
        GestorBaseDatos.conexion.BorrarConexion(path);
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        Tablas t= new Tablas();
        GestorBaseDatos.frame.setPanel(t);
    }//GEN-LAST:event_jButton3MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
