/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestorbasedatos;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gabriela Diaz R
 */
public class Tablas extends javax.swing.JPanel {

    /**
     * Creates new form Tablas
     */
    String tablename = "";
    int index = 0;

    public Tablas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(null);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Listar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(30, 90, 130, 31);

        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jList1);

        add(jScrollPane2);
        jScrollPane2.setBounds(30, 130, 130, 180);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jScrollPane3.setViewportView(jScrollPane1);

        add(jScrollPane3);
        jScrollPane3.setBounds(210, 90, 460, 230);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane4.setViewportView(jTextArea1);

        add(jScrollPane4);
        jScrollPane4.setBounds(30, 450, 230, 220);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Mostrar DDL");
        add(jButton2);
        jButton2.setBounds(30, 400, 230, 40);

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setText("Crear Tabla");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        add(jButton3);
        jButton3.setBounds(400, 470, 200, 40);

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setText("Modificar Tabla");
        add(jButton4);
        jButton4.setBounds(400, 520, 200, 40);

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton5.setText("Agregar Datos");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        add(jButton5);
        jButton5.setBounds(330, 390, 140, 40);

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton6.setText("Borrar Tabla");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        add(jButton6);
        jButton6.setBounds(400, 570, 200, 40);

        jToggleButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jToggleButton1.setText("Back");
        add(jToggleButton1);
        jToggleButton1.setBounds(570, 650, 90, 25);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestorbasedatos/check.png"))); // NOI18N
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        add(jButton7);
        jButton7.setBounds(470, 390, 63, 40);

        jButton8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton8.setText("Modificar Datos");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        add(jButton8);
        jButton8.setBounds(270, 330, 160, 40);

        jButton9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton9.setText("Borrar Datos");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });
        add(jButton9);
        jButton9.setBounds(450, 330, 160, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Tablas");
        add(jLabel1);
        jLabel1.setBounds(80, 20, 140, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestorbasedatos/Firebird_logo.png"))); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(20, 10, 60, 50);
    }// </editor-fold>//GEN-END:initComponents
    public DefaultTableModel Columns(String name) {
        DefaultTableModel model = null;
        ArrayList<String> Col = GestorBaseDatos.conexion.TablesColumnandType(name);
        String[] header = Col.toArray(new String[0]);
        model = new DefaultTableModel(null, header);
        jTable1.setModel(model);

        return model;
    }

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        DefaultListModel listModel = new DefaultListModel();

        ArrayList<String> tmp = new ArrayList<String>();
        tmp = GestorBaseDatos.conexion.ListasTablas();
        int x = 0;
        while (x < tmp.size()) {
            listModel.addElement(tmp.get(x));
            x++;
        }

        jList1.setModel(listModel);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        index = 0;
        tablename = "";
        JList list = (JList) evt.getSource();
        if (evt.getClickCount() == 2) {
            index = list.locationToIndex(evt.getPoint());
            tablename = jList1.getModel().getElementAt(index).toString();
            System.out.print(tablename);
            DefaultTableModel n2 = Columns(tablename);
            ArrayList<String> temp = GestorBaseDatos.conexion.TablesData(tablename);
            int ctn = 0;
            while (ctn < temp.size()) {
                Object[] obj = new Object[GestorBaseDatos.conexion.columnas];
                for (int x = 0; x < GestorBaseDatos.conexion.columnas; x++) {
                    obj[x] = temp.get(ctn);
                    ctn++;
                }
                n2.addRow(obj);
            }
        }


    }//GEN-LAST:event_jList1MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        if (!tablename.equals("")) {
            GestorBaseDatos.conexion.BorrarTabla(tablename, GestorBaseDatos.conexion.url);

            DefaultListModel model = (DefaultListModel) jList1.getModel();
            if (index != -1) {
                model.remove(index);
            }
            DefaultTableModel n2 = (DefaultTableModel) jTable1.getModel();
            n2.setRowCount(0);
            n2.setColumnCount(0);
            index = 0;
            tablename = "";
        }
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        CrearTabla cr = new CrearTabla();
        GestorBaseDatos.frame.setPanel(cr);
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        DefaultTableModel n2 = (DefaultTableModel) jTable1.getModel();
        n2.addRow(new Object[]{});
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        DefaultTableModel n2 = (DefaultTableModel) jTable1.getModel();
        int x = 0;
        String val = "";
        if (n2.getRowCount() != 0) {
            x = n2.getRowCount() - 1;
             ArrayList<String> tipos= GestorBaseDatos.conexion.types(tablename);
            for (int y = 0; y < n2.getColumnCount(); y++) {
              if(tipos.get(y).equals("VARCHAR") ||tipos.get(y).equals("DATE")){
                val += " '" + n2.getValueAt(x, y).toString()+"'";
              }
              else{
                 val += " " + n2.getValueAt(x, y).toString()+" ";
              }
                if (y != n2.getColumnCount()-1) {
                    val += " ,";
                }
            }
              
            GestorBaseDatos.conexion.insertInfoTable(val,tablename);
        }
       
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
      ArrayList<String> tipos= GestorBaseDatos.conexion.types(tablename);
        String PK= GestorBaseDatos.conexion.getprimarykey(tablename)+"= ";
        DefaultTableModel n= new DefaultTableModel();
        int indexC=jTable1.getSelectedColumn();
        int indexR=jTable1.getSelectedRow();
        String name= jTable1.getColumnName(indexC);
        String value=" "+name+"= ";
        int pkindex=0;
        if(tipos.get(indexC).equals("VARCHAR") ||tipos.get(indexC).equals("DATE")){
          value+="'"+ jTable1.getValueAt(indexR, indexC).toString()+" '";
             
        }
        else{
          value+=jTable1.getValueAt(indexR, indexC).toString();  
        }
        
        int count= jTable1.getColumnCount();
        for(int x=0;x<count; x++){
            String tname= jTable1.getColumnName(x);
            if(tname.equals(PK)){
                pkindex=x;
                
            }           
        }
        if(tipos.get(pkindex).equals("VARCHAR") ||tipos.get(pkindex).equals("DATE")){
          PK+="'"+ jTable1.getValueAt(indexR,pkindex).toString()+" '";
             
        }
        else{
          PK +=jTable1.getValueAt(indexR,pkindex).toString(); 
        }
        GestorBaseDatos.conexion.modificarInfoTable(tablename, PK, value);
       
    }//GEN-LAST:event_jButton8MouseClicked

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
         ArrayList<String> tipos= GestorBaseDatos.conexion.types(tablename);
        String PK= GestorBaseDatos.conexion.getprimarykey(tablename)+"= ";
        DefaultTableModel n= new DefaultTableModel();
        int indexR=jTable1.getSelectedRow();
        int pkindex=0;
        int count= jTable1.getColumnCount();
        for(int x=0;x<count; x++){
            String tname= jTable1.getColumnName(x);
            if(tname.equals(PK)){
                pkindex=x;
                
            }           
        }
        if(tipos.get(pkindex).equals("VARCHAR") ||tipos.get(pkindex).equals("DATE")){
          PK+="'"+ jTable1.getValueAt(indexR,pkindex).toString()+" '";
             
        }
        else{
          PK +=jTable1.getValueAt(indexR,pkindex).toString(); 
        }
        GestorBaseDatos.conexion.BorrarInfoTable(tablename, PK);
    }//GEN-LAST:event_jButton9MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
